// <autogenerated>
//   This file was generated by T4 code generator IRepositoryScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using T4Repositories.Models;

namespace T4Repositories.Logic.Repositories
{
	public partial interface IProductRepository : IRepository<Product>
	{
		
	}
}
